/* Datos de proyectos. Edita aquí: youtube (solo el ID del video), github, extra, image, purpose, results.
   Lo que esté vacío se muestra como placeholder. No inventes datos: complétalos cuando los tengas. */
const PROJECTS = [
  { name:"Trabajo de grado: trayectorias de satélite en LEO con IA", status:"En desarrollo",
    desc:"Estimación y corrección predictiva de trayectorias de un satélite en órbita baja (LEO) mediante inteligencia artificial, probada en simulación.",
    solution:["IA de actualización continua que compara la trayectoria real con la mejor trayectoria calculada para detectar errores.","Generación de una corrección predictiva.","Uso de modelos existentes (∂SGP4, PINN, Neural ODE) con software libre o de código abierto."],
    tech:["IA","Simulación","∂SGP4","PINN","Neural ODE"], youtube:"", github:"", extra:"", image:"", purpose:"", results:"" },
  { name:"URC — University Rover Challenge 2027",
    desc:"Participación en un grupo de investigación para el diseño y desarrollo de un rover de exploración.",
    solution:["Desarrollo web Full-Stack (frontend y backend) para la interfaz de control.","Gemelo digital con telemetría en tiempo real y conexión dinámica con el rover.","Integración de modelos de visión por computadora con IA, migrando sistemas a NVIDIA Jetson.","Reconocimiento de códigos ArUco integrado con el sistema de tracción (ROS2)."],
    tech:["Full-Stack","Gemelo digital","Visión por computadora","NVIDIA Jetson","ROS2","Python"], youtube:"", github:"", extra:"", image:"", purpose:"", results:"" },
  { name:"Turbina eólica",
    desc:"Diseño, planeación e implementación completa de una turbina eólica capaz de alimentar una red de 120 V AC / 60 Hz, desde el análisis de inversión hasta la puesta en marcha.",
    solution:["Análisis de inversión.","Diseño y planeación.","Implementación y puesta en marcha."],
    tech:["120 V AC / 60 Hz","Energía eólica"], youtube:"", github:"", extra:"", image:"", purpose:"", results:"" },
  { name:"Sistema de embotellado con PLC Siemens S7-1500",
    desc:"Diseño, control y automatización de un sistema de embotellado con bandas transportadoras, programado y simulado.",
    solution:["Lógica de control y secuencia de operación en TIA Portal.","Uso de variador de frecuencia y servomotor Siemens."],
    tech:["PLC S7-1500","TIA Portal","Variador de frecuencia","Servomotor"], youtube:"", github:"", extra:"", image:"", purpose:"", results:"" },
  { name:"Robot SCARA para manejo y corte de ICOPOR",
    desc:"Diseño e implementación física de un robot SCARA para el manejo y corte automatizado de ICOPOR.",
    solution:["Mecánica y electrónica de potencia.","Sistema de control.","Programación de trayectorias."],
    tech:["Robótica","Electrónica de potencia","Control","Trayectorias"], youtube:"", github:"", extra:"", image:"", purpose:"", results:"" },
  { name:"Ambiente virtual con control interactivo",
    desc:"Ambiente de realidad virtual en Unity que interactúa dinámicamente con un sistema de control real.",
    solution:["Visualización y manipulación del entorno virtual mediante señales de control físico en tiempo real."],
    tech:["Unity","Control en tiempo real"], youtube:"", github:"", extra:"", image:"", purpose:"", results:"" },
  { name:"Robot seguidor de línea",
    desc:"Diseño e implementación física de un robot seguidor de línea con varias estrategias de control implementadas y comparadas.",
    solution:["Control PID.","Servosistema con observador de estado.","Controlador por oscilaciones muertas.","Diseño por lugar geométrico de las raíces (LGR)."],
    tech:["PID","Observador de estado","LGR","Control"], youtube:"", github:"", extra:"", image:"", purpose:"", results:"" },
  { name:"Dron quadrotor",
    desc:"Diseño, simulación e implementación física de un dron quadrotor con control de posición, velocidad, aceleración y trayectorias.",
    solution:["Modelado dinámico del sistema.","Diseño del controlador.","Construcción física del prototipo."],
    tech:["Modelado dinámico","Control","Simulación"], youtube:"", github:"", extra:"", image:"", purpose:"", results:"" },
  { name:"Elevador accionado por motor DC",
    desc:"Diseño, control y automatización de un elevador accionado por motor DC.",
    solution:["[DESCRIPCIÓN DE APORTES]"],
    tech:["Motor DC","Control","Automatización"], youtube:"", github:"", extra:"", image:"", purpose:"", results:"" }
];
